### ISSUE TITLE
Issues with admin menu

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/stickynav#8]
If you have "keep bar at top of page" selected for admin menu (admin/config/administration/admin-bar) and turn on stickynav, stickynav will cover up the admin menu once you start to scroll. 

It would be nice if you could keep both the admin menu AND your regular menu sticky. 

HOWEVER, you can exclude the admin role from using stickynav if it is important for you to keep the admin sticky. So, I think this is a pretty minor issue.

**Comment by ghost** [comment]
I was having this issue, but I figured it out: in the Sticky Nav settings, set the Offset Selector to `#admin-bar`. That calculates the height of the admin-bar and puts the sticky nav item that far from the top of the screen so as not to overlap it.

NOTE: Leave the 'Custom offset' setting blank (this tricked me at first). Hope that helps.

**Comment by ghost** [comment]
Actually, this only works temporarily. After a while (a few refreshes or clicking different links) the admin bar disappears when you scroll down...

**Comment by ghost** [comment]
This patch (modified for Backdrop) seems to fix the issue for me: https://www.drupal.org/files/issues/stickynav-2574207-12.patch
I'll keep testing it, ~but I haven't had the issue I described in https://github.com/backdrop-contrib/stickynav/issues/8#issuecomment-559862693 after applying it~.
EDIT: Nope, problem still happens...
EDIT x2: Now getting around this by adding the following CSS to my theme:
```css
.admin-bar {SELECTOR}.stickynav-active {
  top: 33px;
}
```

Also, discovered another issue with the admin menu in that the `z-index` of the stickynav is `1000` while the `z-index` of the admin bar is `999`. Therefore drop-down menus from the admin bar are hidden behind the sticky nav.
This can be fixed by setting the `z-index` of stickynav to 999.

**Comment by laryn** [comment]
Thanks @stpaultim and @BWPanda!
Is this something that can be consolidated into a PR?

**Comment by laryn** [comment]
Reopening as this now causes display issues if the admin menu is not fixed in position. I'm not seeing a quick way to target this based on CSS alone so maybe need to check the config setting for the admin menu and insert a special bit of CSS if it is fixed in place?

**Comment by laryn** [comment]
I adjusted the example selector to be correct and removed the hard-coded offset in the CSS. I did some testing with that `#admin-menu` selector and a fixed admin menu which seemed to work fine, and a non-fixed admin menu and no selector, which also seemed to work fine. Please open a new issue if there's something I missed!

Also feel free to expand on things in the Wiki:

 - https://github.com/backdrop-contrib/stickynav/wiki
